#!/bin/zsh

export XDG_CONFIG_HOME="$HOME/.config"

export PNPM_HOME="$HOME/.cache"

#android studio
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$XDG_CONFIG_HOME/my_scripts

# brew
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_PIP_INDEX_URL="https://pypi.tuna.tsinghua.edu.cn/simple"

# zsh comp dir
export ZSH_COMPDUMP="$HOME/.cache/.zcompdump-$HOST"

#rust
export RUSTUP_DIST_SERVER="https://rsproxy.cn"
export RUSTUP_UPDATE_ROOT="https://rsproxy.cn/rustup"
export CARGO_UNSTABLE_SPARSE_REGISTRY=true
export PATH=/Users/rick/.cargo/bin:$PATH

#vim
export MYVIMRC="$XDG_CONFIG_HOME/vim/.vimrc"
