#!/bin/zsh

eval "$(/opt/homebrew/bin/brew shellenv)"
export XDG_CONFIG_HOME="$HOME/.config"

export PNPM_HOME="$HOME/.cache"

#android studio
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$XDG_CONFIG_HOME/my_scripts

# zsh comp dir
export ZSH_COMPDUMP="$HOME/.cache/.zcompdump-$HOST"

#rust
export RUSTUP_DIST_SERVER="https://rsproxy.cn"
export RUSTUP_UPDATE_ROOT="https://rsproxy.cn/rustup"
export CARGO_UNSTABLE_SPARSE_REGISTRY=true
export PATH=/Users/rick/.cargo/bin:$PATH

#vim
export MYVIMRC="$XDG_CONFIG_HOME/vim/.vimrc"
