#!/bin/zsh

# Zsh root
ZSHAREDIR=$HOME/.local/share/zsh-nix

git_current_branch() {
	git -C "$1" branch | sed  '/^\*/!d;s/\* //'
}

# git alias
alias ga='git add'
alias gck='git checkout'
alias gcl='git clone --recurse-submodules'
alias gc='git commit --verbose'
alias gc!='git commit --verbose --amend'
alias gstall='git stash --all'
alias gstp='git stash pop'
alias gst='git status'
alias gpr='git pull --rebase'
alias gsu='git submodule update'
alias gsi='git submodule init'
alias gck="git checkout";
alias gsu="git submodule update --remote";
alias gft="git difftool --no-symlinks --dir-diff";
alias glg="git log --graph --abbrev-commit --decorate --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all";
alias ggpush='git push origin "$(git_current_branch)"';

alias cd="z";
alias ll="eza -la --git --git-repos-no-status --classify=always";
# alias ea="lsd -la";
# achrome="open -n /Applications/Google\ Chrome\ Dev.app/ --args --disable-web-security  --user-data-dir=/Users/rick/Downloads/chromeDevData";
alias icat="kitty +kitten icat";
alias vim="nvim";
alias tma="tmux a";
alias tml="tmux ls";
alias tmk="tmux kill-server";
alias lg="lazygit";
alias pm="pnpm";
alias achrome="open -n /Applications/Google\ Chrome\ Dev.app/ --args --disable-web-security  --user-data-dir=/Users/rick/Downloads/chromeDevData";
alias showFiles="defaults write com.apple.finder AppleShowAllFiles -boolean true ; killall Finder";
alias hideFiles="defaults write com.apple.finder AppleShowAllFiles -boolean false ; killall Finder";
alias brewcl="brew cleanup -s --prune=all";
alias brewup="brew upgrade; brewcl";
alias fly="env https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890";
alias fle="export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890";
alias cnpm="npm --registry=https://registry.npmmirror.com  --cache=$HOME/.npm/.cache/cnpm  --disturl=https://npmmirror.com/mirrors/node  --userconfig=$HOME/.cnpmrc";
alias f="yazi";
alias s="kitty +kitten ssh";
alias compose-update="docker compose down && docker compose pull && docker compose up -d";
alias compose-update-sudo="sudo docker compose down && sudo docker compose pull && sudo docker compose up -d";

alias dud="dust -D -d 1";

alias neovim-restore="nvim --headless "+Lazy! restore" +qa"

cowsay "Welcome, Human."

performace_test(){
	hyperfine --runs 10 'zsh -i -c exit'
}

convert_to_hevc() {
  input_filename=$1
  
  if [[ -z "$input_filename" ]]; then
    echo "Usage: convert_to_hevc <input_filename>"
    return 1
  fi

  # if [[ ! -f "$input_filename" ]]; then
  #   echo "Error: File '$input_filename' not found."
  #   return 1
  # fi

  output_filename="hevc_${input_filename}"
  ffmpeg -i $input_filename -c:v hevc_videotoolbox -crf 28 $output_filename
  
  echo "Output generated: $output_filename"
}

cycle(){
	win=$(yabai -m query --windows --window last | jq '.id')

	while : ; do
    	yabai -m window $win --swap prev &> /dev/null
    	if [[ $? -eq 1 ]]; then
        	break
    	fi
	done
}
