export ZSH="$HOME/.oh-my-zsh"
export ZSH_COMPDUMP="$ZSH/cache/.zcompdump-$HOST"

ZSH_THEME="ys"

plugins=(git
	zoxide
	extract
	zsh-autosuggestions
	git-open
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

alias ea="eza -la --git"
alias achrome='open -n /Applications/Google\ Chrome\ Dev.app/ --args --disable-web-security  --user-data-dir=/Users/rick/Downloads/chromeDevData'
alias gsu='git submodule update --remote'
alias gft='git difftool --no-symlinks --dir-diff'
alias glg="git log --graph --abbrev-commit --decorate --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias icat="kitty +kitten icat"
alias vim="NVIM_APPNAME=AstroNvim nvim"
alias vm="nvim"
alias tma="tmux a -t"
alias tml="tmux ls"
#lazygit
alias lg="lazygit"
#pnpm
alias pm="pnpm"
# theme
fpath+=$HOME/.zsh/pure
autoload -U promptinit
promptinit
prompt pure

#yarn
export PATH=$PATH:/Users/rick/.yarn/bin

#nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

#show hide files in finder
alias showFiles="defaults write com.apple.finder AppleShowAllFiles -boolean true ; killall Finder"
alias hideFiles="defaults write com.apple.finder AppleShowAllFiles -boolean false ; killall Finder"

#delete huge amount of files
alias batchDelete="rsync --delete-before -d"

#android studio
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

#ruby
eval "$(rbenv init - zsh)"

#brew
alias brewcl="brew cleanup -s --prune=all"
alias brewup="brew upgrade; brewcl"

#clean
alias cache-clear="yarn cache clean; 
npm cache clean -force;
pnpm store prune;
pod cache clean --all;
brewcl;rm -rf ~/.gradle/cache;
rm -rf ~/Library/Developer/Xcode/DerivedData;
rm -rf ~/Library/Developer/Xcode/Archives;
rm -rf ~/.bun/install/cache/;"

export PATH="/opt/homebrew/opt/protobuf@3/bin:$PATH"

# fq
alias fly="env https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890"
alias fle="export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890"

# brew
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_PIP_INDEX_URL="https://pypi.tuna.tsinghua.edu.cn/simple"

# cnpm
alias cnpm="npm --registry=https://registry.npmmirror.com  --cache=$HOME/.npm/.cache/cnpm  --disturl=https://npmmirror.com/mirrors/node  --userconfig=$HOME/.cnpmrc"
alias cyarn="yarn --registry=https://registry.npmmirror.com"
# alias cpnpm="pnpm --registry https://registry.npmmirror.com"

# for zoxide , have to install fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# make zoxide default
alias cd="z"

# pnpm
export PNPM_HOME="/Users/rick/Library/pnpm"
case ":$PATH:" in
*":$PNPM_HOME:"*) ;;
*) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
# postgresql
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/postgresql@15/lib"
export CPPFLAGS="-I/opt/homebrew/opt/postgresql@15/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/postgresql@15/lib/pkgconfig"
alias pgstart='LC_ALL="C" /opt/homebrew/opt/postgresql@15/bin/postgres -D /opt/homebrew/var/postgresql@15'

#yazi to ya
alias f="yazi"

#rust
export CARGO_HOME="$HOME/.cargo/"
